Repository sacloud/libsacloud, pull requests merged in 2020-05, with the labels that each got.

#559 Add utils/wait
  v2/sacloud/state_test.go
  v2/utils/wait/wait.go
Labels: area/utils, v2

#564 Fix ChangePlan failures in ProxyLB
  v2/internal/define/proxylb.go
  v2/sacloud/naked/proxylb.go
  v2/sacloud/zz_api_ops.go
  v2/sacloud/zz_envelopes.go
Labels: area/definition, area/types, bug, v2

#565 Added test of changing ProxyLB's plan
  v2/sacloud/fake/ops_proxy_lb.go
  v2/sacloud/test/proxylb_op_test.go
Labels: area/test, v2

#567 Fix running godoc
  v2/Makefile
Labels: v2

#569 pkg/mapconv: add ignore tag
  v2/pkg/mapconv/mapconv.go
  v2/pkg/mapconv/mapconv_test.go
Labels: v2

#570 Update dependencies
  v2/go.mod
  v2/go.sum
  v2/internal/tools/gen-api-models/main.go
  v2/sacloud/zz_models.go
Labels: area/utils, v2

#572 Add helper/validate package
  v2/helper/validate/validate.go
  v2/helper/validate/validate_test.go
Labels: area/utils, v2
